// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odrolevdpfpojjdfqczv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kcm9sZXZkcGZwb2pqZGZxY3p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMzU4NzcsImV4cCI6MjA2NjcxMTg3N30.u82Ax85fwK3x_kgiug_nMdDDyoV91p9WTcsVAtlUZps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
